server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10
    timeout: 10s

scrape_configs:
  # Docker service discovery
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: status
            values: [running]
    
    # Filter to only log-generator container
    relabel_configs:
      # Keep only log-generator container
      - source_labels: ['__meta_docker_container_name']
        regex: '/log-generator'
        action: keep
      
      # Add container name as label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      
      # Add container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      
      # Set the log path
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: '/var/lib/docker/containers/$1/*-json.log'
    
    # Pipeline stages to parse logs
    pipeline_stages:
      # Parse Docker JSON format
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      
      # Extract timestamp
      - timestamp:
          source: time
          format: RFC3339Nano
      
      # Parse the actual log content (JSON logs from our app)
      - json:
          expressions:
            timestamp: timestamp
            level: level
            client_ip: client_ip
            user_id: user_id
            method: http.request.method
            status_code: http.response.status_code
            bytes: http.response.bytes
            url: http.url
            message: message
          source: log
      
      # Add extracted fields as labels
      - labels:
          level:
          method:
          status_code:
      
      # Output the log
      - output:
          source: log
